[versions]
# libraries

# plugins
kotlin = "2.0.0"
changelog = "2.2.1"
gradleIntelliJPlugin = "1.17.4"
qodana = "2024.1.9"
kover = "0.8.3"

[libraries]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }